version: '3.2'
services:
  ems-mysql:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cdss_decoupling
  ems:
    image: docker.pkg.github.com/uecit/cdss-ems/latest:pr-6-merge
    ports:
      - "8083:8083"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://ems-mysql:3306/cdss_decoupling
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password
    depends_on: 
      - ems-mysql