# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Docker login
      run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Run Cactus
      run: bash scripts/run-cactus.sh
    - name: Verify
      run: DRIVER_LOCATION=$CHROMEWEBDRIVER mvn -B verify --file pom.xml
    - name: Clean up
      run: docker-compose down
    - name: upload screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshots
        path: target/screenshots/*
    - name: upload report
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: report
        path: target/report/*
